stages:
    - build
cache:
    paths:
        - .m2/

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2"

build_job:
    stage: build
    tags:
        - immersive-runner-cgi
    image: maven:latest
    script:
        - mvn clean package test