  version : "3"
  services:
    employee-service:
      image: employeeservice
      build: employeeservice/
      restart: always
      network_mode: host
      container_name: employeeservice.jar
      ports:
        - "9090:9090"
      expose:
        - 9090

    eureka-service:
      image: eureka
      build: eurekaservice/
      restart: always
      network_mode: host
      container_name: eureka-container
      ports:
        - "8761:8761"
      expose:
        - 8761

    spring-config-server:
      image: config
      build: configserver/
      restart: always
      network_mode: host
      container_name: config-container
      ports:
        - "8888:8888"
      expose:
        - 8888
    api-gateway-service:
      image: zuul
      build: zuulservice/
      restart: always
      network_mode: host
      container_name: zuul-container
      ports:
        - "8081:8081"
      expose:
        - 8081
    springapplication:
      image: springapp
      build: springapp/
      restart: always
      network_mode: host
      container_name: springapp-container
      depends_on:
        - spring-config-server
        - eureka-service
      ports:
        - "8090:8090"
      expose:
        - 8090
