  version : "3"
  services:
    login-service:
      image: loginservice
      build: loginService/
      restart: always
      network_mode: host
      hostname: localhost
      container_name: login-service
      ports:
        - "8081:8081"
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081"]
        interval: 4m30s
        timeout: 10s
        retries: 3

    admin-service:
      image: adminservice
      build: adminService/
      restart: always
      network_mode: host
      hostname: localhost
      container_name: admin-service
      ports:
        - "8082:8082"
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082"]
        interval: 4m30s
        timeout: 10s
        retries: 3

    employee-service:
      image: employeeservice
      build: employeeService/
      restart: always
      network_mode: host
      hostname: localhost
      container_name: employee-service
      ports:
        - "8083:8083"
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8083"]
        interval: 4m30s
        timeout: 10s
        retries: 3

    hr-service:
      image: hrservice
      build: hrService/
      restart: always
      network_mode: host
      hostname: localhost
      container_name: hr-service
      ports:
        - "8084:8084"
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8084"]
        interval: 4m30s
        timeout: 10s
        retries: 3
    gateway:
      image: app/zuul
      container_name: service-gateway
      ports:
        - "8080:8080"
      build:
        context: ./zuulService
        dockerfile: Dockerfile
      network_mode: host
      hostname: localhost
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 4m30s
        timeout: 10s
        retries: 3
    config:
      image: app/config
      container_name: config-service
      ports:
        - "8888:8888"
      build:
        context: ./configServer
        dockerfile: Dockerfile
      network_mode: host
      hostname: localhost
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888"]
        interval: 4m30s
        timeout: 10s
        retries: 3
    discovery:
      image: app/eureka
      container_name: eureka-service
      ports:
        - "8761:8761"
      build:
        context: ./eurekaService
        dockerfile: Dockerfile
      network_mode: host
      hostname: localhost
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761"]
        interval: 4m30s
        timeout: 10s
        retries: 3
