  version : "3"
  services:
    login-service:
      image: loginservice
      build: loginService/
      restart: always
      network_mode: host
      container_name: login-service
      ports:
        - "8091:8091"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8091"]
        interval: 4m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    admin-service:
      image: adminservice
      build: adminService/
      restart: always
      network_mode: host
      container_name: admin-service
      ports:
        - "8092:8092"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8092"]
        interval: 4m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    employee-service:
      image: employeeservice
      build: employeeService/
      restart: always
      network_mode: host
      container_name: employee-service
      ports:
        - "8093:8093"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8093"]
        interval: 4m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    hr-service:
      image: hrservice
      build: hrService/
      restart: always
      network_mode: host
      container_name: hr-service
      ports:
        - "8094:8094"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8094"]
        interval: 4m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    eureka-service:
      image: eureka
      build: eurekaservice/
      restart: always
      network_mode: host
      container_name: eureka-container
      ports:
        - "8761:8761"

    spring-config-server:
      image: config
      build: configserver/
      restart: always
      network_mode: host
      container_name: config-container
      ports:
        - "8888:8888"

    api-gateway-service:
      image: zuul
      build: zuulservice/
      restart: always
      network_mode: host
      container_name: zuul-container
      ports:
        - "8080:8080"
