spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/AQE
    username: chinmay
    password: Root@123
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file: app.log

